services:
  qbittorrent:
    image: qbittorrent:latest
    container_name: qbittorrent
    environment:
      - DISPLAY=:0
      - PUID=1000
      - PGID=1000
    network_mode: host
    volumes:
      - ~/qbittorrent:/root/Downloads
      - ~/qbitconfig:/root/.config/qBittorrent
    ports:
      - 9117:9117
      - 9117:9117/udp
      - 6881:6881
      - 6881:6881/udp
    restart: always
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - ~/jackett:/config
    ports:
      - "9117:9117"
    restart: always
