services:
  qbittorrent:
    image: qbittorrent:latest
    container_name: qbittorrent
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    volumes:
      - ./qbittorrent:/root/Downloads
      - ./qbitconfig/config:/root/.config/qBittorrent
      - ./qbitconfig/local:/root/.local/share/qBittorrent
    restart: always
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - ./jackett:/config
    ports:
      - "9117:9117"
    restart: always
    
